.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lava_qt test_lava_qt
clean: FORCE
	$(MAKE) -C .. lava_qt_clean test_lava_qt_clean
check: FORCE
	$(MAKE) -C .. test_lava_qt_check
lava-qt lava-qt.exe: FORCE
	 $(MAKE) -C .. lava_qt
